name: Sync To Gitee

on: [ push, delete, create ]

concurrency:
  group: git-mirror

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:451008604/blog-images.git"
          destination-repo: "git@gitee.com:guohaoqin/blog-images.git"
